issuer: 'http://localhost:5556/dex'

storage:
  type: memory

web:
  http: 0.0.0.0:5556
  allowedOrigins:
    - 'http://localhost:5173'

staticClients:
  - id: example-app-id
    redirectURIs:
      - 'client_id'
    name: 'sobaka'
    secret: client_id

connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: client_id
      clientSecret: client_id
      redirectURI: 'http://localhost:5556/dex/callback'
